### ISSUE TITLE
snapcraft-preload fails to build on arm64 and ppc64el

### ISSUE THREAD

**Issue by jdstrand** [sergiusens/snapcraft-preload#13]
Using the following in snapcraft.yaml:

```
...
  after:
  - snapcraft-preload
```

only amd64, i386 and armhf build. Eg:
- amd64: https://launchpadlibrarian.net/317293325/buildlog_snap_ubuntu_xenial_amd64_review-tools_BUILDING.txt.gz
- armhf: https://launchpadlibrarian.net/317293424/buildlog_snap_ubuntu_xenial_armhf_review-tools_BUILDING.txt.gz
- i386: https://launchpadlibrarian.net/317293369/buildlog_snap_ubuntu_xenial_i386_review-tools_BUILDING.txt.gz

but other architectures fail:
- arm64: https://launchpadlibrarian.net/317293239/buildlog_snap_ubuntu_xenial_arm64_review-tools_BUILDING.txt.gz
- ppc64el https://launchpadlibrarian.net/317293236/buildlog_snap_ubuntu_xenial_ppc64el_review-tools_BUILDING.txt.gz

Recent updates seem to cause arm64 and ppc64el to fail. I used to be able to use this in the snapcraft.yaml for armhf, arm64, i386 and ppc64el to build:

```
preload:
  source: https://github.com/sergiusens/snapcraft-preload.git
  source-commit: fc60c1d58bdb90a98622179fd3ecfdf9e35e57c3
  source-type: git
  plugin: cmake
```

and this for amd64:
```
preload:
  source: https://github.com/sergiusens/snapcraft-preload.git
  source-commit: fc60c1d58bdb90a98622179fd3ecfdf9e35e57c3
  source-type: git
  plugin: cmake
  # Uncomment the following for amd64 (LP: #1671238)
  build-packages:
  - libc6-dev-i386
  - libc6-dev-x32
  - gcc-5-multilib
  - gcc-multilib
```

**Comment by anonymouse64** [comment]
What seems to work for me on arm64, armhf, i386 and am64 is:

```yaml
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - to arm64:
          - g++-multilib-arm-linux-gnueabihf
          - gcc-multilib-arm-linux-gnueabihf
      - else:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - to amd64:
          - lib32stdc++6
```
